-- ============================================================
-- 027 — Multi-tenant company email provisioning
-- ============================================================
-- Schema for the "every joining agent gets a company email"
-- system documented in docs/COMPANY-EMAIL-ARCHITECTURE.md.
--
-- Two tables:
--   1. companies — one row per company/brand using the platform
--      (InvestPro Realty today; LYMX, CFS, etc. tomorrow)
--   2. agent_emails — one row per provisioned email address
--
-- Background: Kenny 2026-05-02 — wants automated company email
-- provisioning that scales to thousands of agents across multiple
-- companies. Cloudflare Email Routing (inbound) + Amazon SES
-- (outbound) — see architecture doc.
-- ============================================================


-- ----------------------------------------------------------------
-- 1. companies — one row per business using the platform
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS companies (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug                        TEXT UNIQUE NOT NULL,        -- 'investpro', 'lymx', 'cfs'
  name                        TEXT NOT NULL,               -- 'InvestPro Realty'
  primary_domain              TEXT NOT NULL UNIQUE,        -- 'investprorealty.net'
  tagline                     TEXT,                        -- shown in onboarding emails

  -- Cloudflare Email Routing config
  cloudflare_zone_id          TEXT,                        -- from CF dashboard → Overview → API
  cloudflare_setup_complete   BOOLEAN DEFAULT FALSE,       -- routes can be added when true

  -- Amazon SES config (per company so different SES regions/accounts can be used)
  ses_region                  TEXT DEFAULT 'us-east-1',
  ses_domain_verified         BOOLEAN DEFAULT FALSE,       -- domain identity verified in SES
  ses_production_access       BOOLEAN DEFAULT FALSE,       -- moved out of sandbox

  -- Branding for outbound onboarding emails
  support_phone               TEXT,
  support_email               TEXT,                        -- e.g. info@investprorealty.net
  brand_color                 TEXT DEFAULT '#1F4FC1',

  active                      BOOLEAN NOT NULL DEFAULT TRUE,
  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_companies_active
  ON companies(active) WHERE active = TRUE;

DROP TRIGGER IF EXISTS trg_companies_touch ON companies;
CREATE TRIGGER trg_companies_touch
  BEFORE UPDATE ON companies
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();


-- ----------------------------------------------------------------
-- 2. agent_emails — one row per provisioned company email
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agent_emails (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  profile_id                  UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  company_id                  UUID NOT NULL REFERENCES companies(id),

  -- The generated address
  local_part                  TEXT NOT NULL,               -- 'helen.smith' or 'helen.smith.2'
  full_email                  TEXT NOT NULL UNIQUE,        -- 'helen.smith@investprorealty.net'
  forward_to                  TEXT NOT NULL,               -- agent's personal email

  -- Where the application originated (audit trail for "who promoted them")
  source_application_id       UUID REFERENCES agent_applications(id) ON DELETE SET NULL,

  -- Lifecycle status
  status                      TEXT NOT NULL DEFAULT 'pending',
                                -- pending → active → suspended → deleted
  status_reason               TEXT,                        -- explanation when suspended

  -- Cloudflare integration (saved so we can DELETE the route on offboarding)
  cloudflare_route_id         TEXT,
  cloudflare_synced_at        TIMESTAMPTZ,
  cloudflare_last_error       TEXT,

  -- SES integration (outbound)
  ses_identity_arn            TEXT,                        -- AWS resource identifier
  ses_identity_verified       BOOLEAN DEFAULT FALSE,
  ses_smtp_username           TEXT,                        -- generated by SES
  ses_smtp_password_set_at    TIMESTAMPTZ,                 -- track when creds last rotated
  ses_synced_at               TIMESTAMPTZ,
  ses_last_error              TEXT,

  -- Lifecycle timestamps
  provisioned_at              TIMESTAMPTZ,                 -- when CF route was added
  onboarding_email_sent_at    TIMESTAMPTZ,                 -- when we mailed setup instructions
  agent_acknowledged_at       TIMESTAMPTZ,                 -- agent confirmed Gmail send-as works
  suspended_at                TIMESTAMPTZ,
  suspended_by_id             UUID REFERENCES profiles(id) ON DELETE SET NULL,

  created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE(profile_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_agent_emails_profile
  ON agent_emails(profile_id);
CREATE INDEX IF NOT EXISTS idx_agent_emails_company
  ON agent_emails(company_id);
CREATE INDEX IF NOT EXISTS idx_agent_emails_status
  ON agent_emails(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_emails_full_email
  ON agent_emails(LOWER(full_email));

DROP TRIGGER IF EXISTS trg_agent_emails_touch ON agent_emails;
CREATE TRIGGER trg_agent_emails_touch
  BEFORE UPDATE ON agent_emails
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

COMMENT ON COLUMN agent_emails.cloudflare_route_id IS
  'Stable ID returned by Cloudflare on route create. Saved so we can DELETE the route exactly when offboarding the agent.';

COMMENT ON COLUMN agent_emails.ses_smtp_username IS
  'Per-agent SMTP credentials generated by SES "Get SMTP credentials". Encrypted at rest if pgcrypto is enabled. The matching password is stored only as a one-way verification timestamp here — the actual password is delivered to the agent in the onboarding email and never persisted.';


-- ----------------------------------------------------------------
-- 3. Audit triggers — both tables get full edit history
-- ----------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_companies ON companies;
CREATE TRIGGER trg_audit_companies
  AFTER INSERT OR UPDATE OR DELETE ON companies
  FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();

DROP TRIGGER IF EXISTS trg_audit_agent_emails ON agent_emails;
CREATE TRIGGER trg_audit_agent_emails
  AFTER INSERT OR UPDATE OR DELETE ON agent_emails
  FOR EACH ROW EXECUTE FUNCTION audit_trigger_fn();


-- ----------------------------------------------------------------
-- 4. RLS
-- ----------------------------------------------------------------
ALTER TABLE companies ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_emails ENABLE ROW LEVEL SECURITY;

-- Companies — broker/compliance/admin_onsite read all, broker can write
DROP POLICY IF EXISTS companies_managers_read ON companies;
CREATE POLICY companies_managers_read ON companies
  FOR SELECT TO authenticated
  USING (current_user_role() IN ('broker', 'compliance', 'admin_onsite'));

DROP POLICY IF EXISTS companies_broker_write ON companies;
CREATE POLICY companies_broker_write ON companies
  FOR ALL TO authenticated
  USING (current_user_role() = 'broker')
  WITH CHECK (current_user_role() = 'broker');

-- agent_emails — managers see all, agents see only their own
DROP POLICY IF EXISTS agent_emails_managers_all ON agent_emails;
CREATE POLICY agent_emails_managers_all ON agent_emails
  FOR ALL TO authenticated
  USING (current_user_role() IN ('broker', 'compliance', 'admin_onsite'))
  WITH CHECK (current_user_role() IN ('broker', 'compliance', 'admin_onsite'));

DROP POLICY IF EXISTS agent_emails_self_read ON agent_emails;
CREATE POLICY agent_emails_self_read ON agent_emails
  FOR SELECT TO authenticated
  USING (profile_id = auth.uid());


-- ----------------------------------------------------------------
-- 5. Seed InvestPro company
-- ----------------------------------------------------------------
-- The Cloudflare zone ID and SES verification will be filled in by
-- Kenny after he completes the per-domain setup steps in the
-- architecture doc. For now, the row exists so the platform code
-- can reference it.
INSERT INTO companies (slug, name, primary_domain, tagline, support_phone, support_email)
VALUES (
  'investpro',
  'InvestPro Realty',
  'investprorealty.net',
  'Las Vegas Real Estate — Sales, Property Management, Agent Careers',
  '702-816-5555',
  'info@investprorealty.net'
)
ON CONFLICT (primary_domain) DO NOTHING;


-- ----------------------------------------------------------------
-- 6. Helper function: pick a non-conflicting local_part
-- ----------------------------------------------------------------
-- Generates 'first.last' with a numeric suffix on collision.
-- Called by the platform when provisioning an email.
CREATE OR REPLACE FUNCTION agent_email_pick_local_part(
  p_first_name TEXT,
  p_last_name  TEXT,
  p_domain     TEXT
) RETURNS TEXT LANGUAGE plpgsql AS $$
DECLARE
  v_base    TEXT;
  v_n       INT := 1;
  v_test    TEXT;
  v_full    TEXT;
BEGIN
  -- Lowercase, strip non-alphanumeric except dot/hyphen, dot between first+last
  v_base := lower(
    regexp_replace(coalesce(p_first_name, ''), '[^a-zA-Z]', '', 'g')
    || '.'
    || regexp_replace(coalesce(p_last_name, ''), '[^a-zA-Z]', '', 'g')
  );
  IF v_base = '.' OR length(v_base) < 3 THEN
    RAISE EXCEPTION 'cannot derive a usable local-part from "%" / "%"', p_first_name, p_last_name;
  END IF;

  v_test := v_base;
  v_full := v_test || '@' || p_domain;
  WHILE EXISTS (SELECT 1 FROM agent_emails WHERE LOWER(full_email) = LOWER(v_full)) LOOP
    v_n := v_n + 1;
    v_test := v_base || '.' || v_n::text;
    v_full := v_test || '@' || p_domain;
    IF v_n > 99 THEN
      RAISE EXCEPTION 'too many collisions for "%"', v_base;
    END IF;
  END LOOP;
  RETURN v_test;
END;
$$;

GRANT EXECUTE ON FUNCTION agent_email_pick_local_part(TEXT, TEXT, TEXT) TO authenticated;


-- ----------------------------------------------------------------
-- 7. Verify
-- ----------------------------------------------------------------
SELECT slug, name, primary_domain, active FROM companies;
SELECT 'agent_emails columns' AS check, count(*) AS num_columns
  FROM information_schema.columns WHERE table_name = 'agent_emails';
