/* ============================================================
 * Subscriber sign-up handler
 * ============================================================
 * Endpoint: https://investpro-realty.netlify.app/.netlify/functions/subscribe-signup
 *
 * Called from the public sign-up form on /subscribe.html.
 * Public endpoint — no auth required (it IS the front door).
 *
 * What it does:
 *   1. Validates submission (required fields, email format, honeypot)
 *   2. Resolves optional sponsor code (AGT-XXXXX or SUB-XXXXX) to
 *      sponsor_agent_id / sponsor_subscriber_id
 *   3. Inserts a row into `subscribers` via service-role
 *   4. Awards 100-LYMX welcome bonus via award_lymx() — Powered by LYMX
 *   5. Awards 50 LYMX referral bonus to the sponsor (if any)
 *   6. Sends a welcome email to the new subscriber via Resend
 *   7. Notifies Kenny so he sees the signup in real time
 *   8. Returns { ok: true, share_code, id } so the form JS can
 *      redirect to /forms/subscriber-welcome.html
 *
 * Required Netlify env vars:
 *   SUPABASE_URL
 *   SUPABASE_SERVICE_ROLE_KEY
 *   RESEND_API_KEY
 *   SUBSCRIBE_RECIPIENT_EMAIL  (defaults to zhongkennylin@gmail.com)
 *   FROM_EMAIL                 (defaults to onboarding@resend.dev)
 * ============================================================ */

const { createClient } = require('@supabase/supabase-js');

exports.handler = async (event) => {
  if (event.httpMethod === 'OPTIONS') return cors(204, '');
  if (event.httpMethod !== 'POST')    return cors(405, JSON.stringify({ ok: false, error: 'Method Not Allowed' }));

  let body;
  try { body = JSON.parse(event.body || '{}'); }
  catch { return cors(400, JSON.stringify({ ok: false, error: 'Invalid JSON' })); }

  // Honeypot: bots tend to fill every field.
  if (body.website || body.fax) {
    console.log('subscribe-signup: honeypot hit, dropping silently');
    return cors(200, JSON.stringify({ ok: true, share_code: null }));
  }

  const full_name         = String(body.full_name || '').trim();
  const email             = String(body.email     || '').trim().toLowerCase();
  const phone             = String(body.phone     || '').trim() || null;
  const sponsor_code      = (String(body.sponsor_code || '').trim().toUpperCase()) || null;
  const newsletter_opt_in = body.newsletter_opt_in !== false;       // default true
  const source            = String(body.source       || 'website').trim();
  const source_url        = String(body.source_url   || '').trim() || null;
  const utm_source        = String(body.utm_source   || '').trim() || null;
  const utm_medium        = String(body.utm_medium   || '').trim() || null;
  const utm_campaign      = String(body.utm_campaign || '').trim() || null;

  if (!full_name) return cors(400, JSON.stringify({ ok: false, error: 'Full name required' }));
  if (!email || !email.includes('@')) {
    return cors(400, JSON.stringify({ ok: false, error: 'Valid email required' }));
  }

  const SUPABASE_URL = process.env.SUPABASE_URL;
  const SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!SUPABASE_URL || !SERVICE_KEY) {
    console.error('subscribe-signup: missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY');
    return cors(500, JSON.stringify({ ok: false, error: 'Server not configured' }));
  }

  const admin = createClient(SUPABASE_URL, SERVICE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false }
  });

  // ---- Duplicate check ----
  const { data: existing } = await admin
    .from('subscribers')
    .select('id, share_code, status')
    .eq('email', email)
    .maybeSingle();

  if (existing && existing.status !== 'unsubscribed') {
    // Idempotent: just return their existing share code so the form can
    // still redirect to the welcome page.
    return cors(200, JSON.stringify({
      ok: true,
      already_subscribed: true,
      id: existing.id,
      share_code: existing.share_code
    }));
  }

  // ---- Sponsor lookup ----
  let sponsor_agent_id = null;
  let sponsor_subscriber_id = null;
  if (sponsor_code) {
    if (sponsor_code.startsWith('AGT-')) {
      const { data: a } = await admin
        .from('agents')
        .select('id')
        .eq('agent_share_code', sponsor_code)
        .maybeSingle();
      if (a && a.id) sponsor_agent_id = a.id;
    } else if (sponsor_code.startsWith('SUB-')) {
      const { data: s } = await admin
        .from('subscribers')
        .select('id, status')
        .eq('share_code', sponsor_code)
        .maybeSingle();
      if (s && s.id && s.status === 'active') sponsor_subscriber_id = s.id;
    }
  }

  // ---- Insert subscriber (share_code is auto-generated by trigger) ----
  const { data: inserted, error: insErr } = await admin
    .from('subscribers')
    .insert({
      email, full_name, phone,
      sponsor_agent_id, sponsor_subscriber_id,
      status: 'active',
      source, source_url,
      utm_source, utm_medium, utm_campaign,
      newsletter_opt_in,
      events_opt_in: true
    })
    .select('id, share_code')
    .single();

  if (insErr) {
    console.error('subscribe-signup: insert failed', insErr);
    return cors(500, JSON.stringify({ ok: false, error: 'Could not create subscription: ' + insErr.message }));
  }

  const newId     = inserted.id;
  const shareCode = inserted.share_code;

  // ---- Award welcome bonus (100 LYMX, Powered by LYMX) ----
  const { error: bonusErr } = await admin.rpc('award_lymx', {
    p_subscriber_id:   newId,
    p_lymx:            100,
    p_source:          'signup_bonus',
    p_source_ref_id:   null,
    p_source_ref_type: 'signup',
    p_description:     'Welcome bonus — thanks for joining InvestPro (Powered by LYMX)'
  });
  if (bonusErr) console.error('subscribe-signup: welcome bonus failed', bonusErr);

  // ---- Sponsor referral credit (50 LYMX to subscriber sponsor) ----
  if (sponsor_subscriber_id) {
    const { error: refErr } = await admin.rpc('award_lymx', {
      p_subscriber_id:   sponsor_subscriber_id,
      p_lymx:            50,
      p_source:          'referral_signup',
      p_source_ref_id:   newId,
      p_source_ref_type: 'subscriber',
      p_description:     `Referral signup: ${full_name}`
    });
    if (refErr) console.error('subscribe-signup: sponsor credit failed', refErr);
  }
  // Note: sponsor_agent_id pays the agent later, when this subscriber
  // converts to an actual agent or transacting client. No immediate
  // LYMX award needed here.

  // ---- Mark welcome_email_sent_at + send emails ----
  const RESEND_API_KEY = process.env.RESEND_API_KEY;
  const FROM_EMAIL     = process.env.FROM_EMAIL || 'InvestPro Realty <onboarding@resend.dev>';
  const NOTIFY_TO      = process.env.SUBSCRIBE_RECIPIENT_EMAIL || 'zhongkennylin@gmail.com';

  if (RESEND_API_KEY) {
    const firstName = full_name.split(' ')[0] || 'there';
    const shareLink = (source_url ? new URL(source_url).origin : 'https://investprorealty.net')
                      + '/subscribe.html?ref=' + encodeURIComponent(shareCode);

    const welcomeHtml = `
      <div style="font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; max-width: 560px; padding: 2rem; color: #1F2937;">
        <h1 style="font-family: Georgia, serif; color: #1F4FC1; margin: 0 0 .5rem;">Welcome to InvestPro, ${escapeHtml(firstName)}!</h1>
        <p style="font-size: 16px; line-height: 1.55;">Your account is active. <strong>100 LYMX</strong> have just landed in your wallet — redeemable against InvestPro fees and across the LYMX network. <em>Powered by LYMX.</em></p>
        <div style="background:#FFFCF0; border:1px dashed #FFD66B; border-radius:6px; padding:1.25rem; text-align:center; margin: 1.25rem 0;">
          <div style="font-size:11px; letter-spacing:.12em; color:#92400E; text-transform:uppercase; font-weight:700;">Your Share Code</div>
          <div style="font-family: Georgia, serif; font-size:1.8rem; color:#1F4FC1; letter-spacing:.05em; margin:.4rem 0; font-weight:700;">${escapeHtml(shareCode)}</div>
          <div style="font-size:12px; color:#6B7280;">Share <a href="${escapeHtml(shareLink)}" style="color:#1F4FC1;">${escapeHtml(shareLink)}</a></div>
        </div>
        <p style="font-size: 14px; line-height: 1.55;">When a friend signs up using your code, you earn <strong>50 LYMX</strong>. If they later become an InvestPro agent, you earn <strong>500 LYMX more</strong>. And every fee you ever pay InvestPro — application, transaction, PM, agent dues — earns you LYMX cashback.</p>
        <p style="font-size: 14px; line-height: 1.55;">In the meantime — keep an eye on your inbox for new listings, market briefings, and event invites.</p>
        <p style="font-size: 14px; color:#6B7280; margin-top:2rem;">— InvestPro Realty<br/>3601 W Sahara Ave, Suite 207<br/>Las Vegas, NV 89102 · 702-816-5555</p>
        <p style="font-size: 11px; color:#9aa3bd; margin-top:1.5rem;">You're receiving this because you signed up at investprorealty.net. Cashback rewards Powered by LYMX (<a href="https://getlymx.com" style="color:#9aa3bd;">getlymx.com</a>). Unsubscribe anytime by replying "unsubscribe".</p>
      </div>
    `;

    try {
      const res = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          from: FROM_EMAIL,
          to: [email],
          subject: `Welcome to InvestPro, ${firstName} — your 100 LYMX are in 🎉`,
          html: welcomeHtml
        })
      });
      if (res.ok) {
        await admin.from('subscribers').update({ welcome_email_sent_at: new Date().toISOString() }).eq('id', newId);
      } else {
        console.error('subscribe-signup: welcome email failed', await res.text());
      }
    } catch (err) {
      console.error('subscribe-signup: welcome email threw', err);
    }

    // Notify Kenny
    try {
      const notifyHtml = `
        <div style="font-family: -apple-system, Segoe UI, Roboto, Arial, sans-serif; max-width:560px; padding:1.5rem; color:#1F2937;">
          <h2 style="font-family: Georgia, serif; color:#1F4FC1; margin:0 0 .5rem;">New subscriber signup</h2>
          <table style="width:100%; border-collapse:collapse; font-size:14px;">
            <tr><td style="padding:.35rem .5rem; background:#F7F8FB; font-weight:600; width:140px;">Name</td><td style="padding:.35rem .5rem;">${escapeHtml(full_name)}</td></tr>
            <tr><td style="padding:.35rem .5rem; background:#F7F8FB; font-weight:600;">Email</td><td style="padding:.35rem .5rem;">${escapeHtml(email)}</td></tr>
            <tr><td style="padding:.35rem .5rem; background:#F7F8FB; font-weight:600;">Phone</td><td style="padding:.35rem .5rem;">${escapeHtml(phone || '—')}</td></tr>
            <tr><td style="padding:.35rem .5rem; background:#F7F8FB; font-weight:600;">Share code</td><td style="padding:.35rem .5rem;">${escapeHtml(shareCode)}</td></tr>
            <tr><td style="padding:.35rem .5rem; background:#F7F8FB; font-weight:600;">Sponsor</td><td style="padding:.35rem .5rem;">${escapeHtml(sponsor_code || '—')}${sponsor_agent_id ? ' (matched agent)' : ''}${sponsor_subscriber_id ? ' (matched subscriber)' : ''}</td></tr>
            <tr><td style="padding:.35rem .5rem; background:#F7F8FB; font-weight:600;">Source</td><td style="padding:.35rem .5rem;">${escapeHtml(source)} · ${escapeHtml(utm_source || '')} ${escapeHtml(utm_campaign || '')}</td></tr>
          </table>
        </div>
      `;
      await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: { 'Authorization': `Bearer ${RESEND_API_KEY}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({
          from: FROM_EMAIL,
          to: [NOTIFY_TO],
          reply_to: email,
          subject: `[InvestPro] New subscriber: ${full_name}`,
          html: notifyHtml
        })
      });
    } catch (err) {
      console.error('subscribe-signup: notify email threw', err);
    }
  }

  return cors(200, JSON.stringify({
    ok: true,
    id: newId,
    share_code: shareCode
  }));
};

function cors(statusCode, body) {
  return {
    statusCode,
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST, OPTIONS',
      'Access-Control-Allow-Headers': 'Content-Type'
    },
    body
  };
}

function escapeHtml(s) {
  return String(s == null ? '' : s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
